[package]
name = "blazebooru_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blazebooru_common = { path = "../common" }
blazebooru_models = { path = "../models" }
blazebooru_store = { path = "../store" }
anyhow = "1.0.65"
argon2 = "0.4.1"
bytes = "1.2.1"
chrono = "0.4.22"
futures-core = "0.3.24"
futures-util = "0.3.24"
image = { version = "0.24.4", features = ["webp-encoder"] }
once_cell = "1.15.0"
regex = "1.6.0"
serde = "1.0.145"
serde_json = "1.0.85"
tokio = "1.21.2"
tracing = "0.1.37"
uuid = { version = "1.2.0", features = ["v4"] }
