[package]
name = "blazebooru_common"
version = "0.1.0"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blazebooru_models = { path = "../models" }
anyhow = "1.0.65"
blake3 = "1.3.1"
bytes = "1.2.1"
chrono = { version = "0.4.22", features = ["serde"] }
futures-core = "0.3.24"
futures-util = "0.3.24"
tokio = "1.21.2"
tokio-util = "0.7.4"
tracing = "0.1.37"
